# Generated by Django 3.0 on 2019-12-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_friends'),
        ('blog', '0002_comment_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='users_liked',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
