# Generated by Django 3.0 on 2019-12-23 08:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191213_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
