# Generated by Django 3.0 on 2019-12-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191223_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='path',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='blog.Comment'),
        ),
    ]
